Simplifications and clean up experience

diff --git a/InstallPiStrong b/InstallPiStrong
--- a/InstallPiStrong
+++ b/InstallPiStrong
@@ -4,12 +4,10 @@
 # Performs the following tasks
 #   Ensures required packages are installed
 #       On Raspbian these are: Apt-get install libgmp10 libgmp-dev libsystemd-dev libssl-dev
-#   Creates a work directory (~/piStrong)
+#   Creates a work directory: $PISTRONGOOT/piStrong (defaults to /root/piStrong)
 #   Downloads and bunzip2 the current released strongswan bits 
 #   Builds strongswan
 #   Installs into the system
-#   Creates /etc/swanctl/conf.d/pistrong-ServerConnection.conf
-#   Creates root CA and VPN cert
 # Use pistrong to manage users and certificates
 # Start and stop the VPN via: 'sudo pistrong service start' and 'sudo pistrong service stop' ...
 #   ...or 'sudo systemctl start strongswan' and 'sudo systemctl stop strongswan'
@@ -44,77 +42,18 @@ function askyn() {
 }
 
 function askin() {
-    local ans
-    echo -n "$1 "; read -n 1 ans
+    local ans sw=""
+    # sw="-n 1"
+    echo -n "$1 "; read $sw ans
 }
 
 function askinall() {
-    if [ "$cmd" == "all" ]
-    then
-	# Flush input in case of typeahead
-	while read -e -t 0.1 ; do : ; done
-	askin "$1"
-    fi
+# Asks only if started with 'allx'
+    [ "$cmd" == "allx" ] && askin "$1"
 }
 
 function gotoBuildDir() {
-    cd ~/piStrong
-    for i in strongswan-*; do [ -d "$i" ] && cd $i ; done
-}
-
-function emitFirewall() {
-
-    getosdistro
-    case "$osdistro" in
-	debian|raspbian)
-	    [ -f /etc/swanctl/pistrong/iptables ] && return
-	    echo "Creating iptables POSTROUTING for strongSwan"
-	    echo "  See /etc/swanctl/pistrong/iptables"
-	    cat > /etc/swanctl/pistrong/iptables <<EOF
-#  Add the necessary iptables routes to enable VPN routing to the internet
-
-*nat
-:POSTROUTING ACCEPT [0:0]
--A POSTROUTING -s $vpnsubnet -o eth0 -m policy --dir out --pol ipsec -j ACCEPT
--A POSTROUTING -s $vpnsubnet -o eth0 -j MASQUERADE
-COMMIT
-EOF
-	    [ -f /etc/systemd/system/pistrong-iptables-load.service ] && return
-	    cat > /etc/systemd/system/pistrong-iptables-load.service <<EOF
-[Unit]
-Description=Load iptables for strongSwan
-Requires=network-online.target
-
-[Service]
-ExecStart=/sbin/iptables-restore /etc/swanctl/pistrong/iptables
-User=root
-StandardInput=null
-StandardOutput=null
-StandardError=null
-Restart=on-failure
-
-[Install]
-WantedBy=multi-user.target
-
-EOF
-	    chmod 644 /etc/systemd/system/pistrong-iptables-load.service
-	    echo "** I have created the service pistrong-iptables-load, but it is not enabled"
-	    echo "** If you have another way to load iptables, you must add the code from /etc/swanctl/pistrong/iptables to it"
-	    echo "** Otherwise you must sudo systemctl enable pistrong-iptables-load"
-	    ;;
-	*)
-	    echo "% You must manually add iptables POSTROUTING entries for strongSwan"
-	    echo "  and in such a way that they will be instantiated when the system restarts."
-	    echo "  These entries enable VPN routing to the internet."
-	    echo ""
-	    echo "Your iptables *nat POSTROUTING chain must contain:"
-	    echo "*nat"
-	    echo ":POSTROUTING ACCEPT [0:0]"
-	    echo "-A POSTROUTING -s $vpnsubnet -o eth0 -m policy --dir out --pol ipsec -j ACCEPT"
-	    echo "-A POSTROUTING -s $vpnsubnet -o eth0 -j MASQUERADE"
-	    echo "COMMIT"
-	    ;;
-    esac
+    cd $PISTRONGROOT/piStrong/strongswan-$ssver
 }
 
 function DoPreReqs() {
@@ -134,10 +73,10 @@ function DoPreReqs() {
             echo "I'll try to install the required packages, but this is incomplete"
             yum install gcc gmp-devel.x86_64 systemd-devel.x86_x64 openssl-devel.x86_64
             echo "Check above to ensure everything got installed"
-            echo ">> You'll need to install python3 and pexpect if they are not already installed"
+            echo "** You'll need to install python3 and pexpect if they are not already installed"
             ;;
         debian|raspbian)
-            echo ">> Ensure your Pi is up to date"
+            echo "** Ensure your Pi is up to date"
             echo " Your Pi must be up to date with the Raspbian repositories by using these commands"
 	    echo ""
             echo "    sudo apt-get update"
@@ -148,15 +87,15 @@ function DoPreReqs() {
             echo ""
             if askyn "Press y to Continue, n to exit and update your Pi" "-n 1"
             then
-		[ "$cmd" == "allx" ] && ally="-y" || ally=""
+		[ "$cmd" == "all" ] && ally="-y" || ally=""
                 echo ""
                 for p in libgmp10 libgmp-dev libsystemd-dev libssl-dev python3-pexpect zip ; do
                     if ! dpkg-query -s $p > /dev/null 2>&1
                     then
-                        echo ">> Installing package $p"
+                        echo "Installing package $p"
                         apt-get $ally install $p
                     else
-                        echo ">> Package $p already installed"
+                        echo "Package $p already installed"
                     fi
                 done
             else
@@ -179,118 +118,124 @@ function DoPreReqs() {
 }
 
 function DoDownload() {
-    cd ~/
+    cd $PISTRONGROOT
     getssver
 #    ssver="5.6.3"  # If you want a specific version (and it's still available, of course)
-    echo "% Using Strongswan version $ssver"
-    askinall "Press any key to start Strongswan download: "
     echo ""
+    echo "Using Strongswan version $ssver"
+    echo ""
+    echo "** The strongSwan download/build process can take several minutes (fast RPi4)"
+    echo "   or close to an hour (RPi0W)."
+    echo ""
+    [ -f strongswan-$ssver.tar.bz2 ] && askinall "Press Enter to start Strongswan download: " && echo ""
     [ ! -d piStrong ] && mkdir piStrong
-    cd piStrong
+    cd ./piStrong
     [ -d strongswan-$ssver ] && rm -rf strongswan-$ssver
     if [ ! -f strongswan-$ssver.tar.bz2 ]
     then
 	curl -L https://download.strongswan.org/strongswan-$ssver.tar.bz2 -o strongswan-$ssver.tar.bz2
     else
-	echo "% strongSwan $ssver .tar.bz2 file already exists here; using it"
+	echo ""
+	echo "Using found strongSwan tar archive $ssver.tar.bz2"
     fi
-    askinall "Press any key to continue: "
+#    askinall "Press Enter to unpack the sources: "
     echo ""
-    tar -xjvf strongswan-$ssver.tar.bz2
+    [ -f pistrong-untar.log ] && rm -f pistrong-untar.log
+    echo "** $(date +'%Y-%m-%d %H:%M:%S') Unpacking source archive [Log: $PSDIR/pistrong-untar.log]"
+    tar -xjvf strongswan-$ssver.tar.bz2 > pistrong-untar.log
 #    curl -L https://download.strongswan.org/strongswan-$ssver.tar.bz2 | tar -xjvf -
 }
 
 function DoPreConf() {
     gotoBuildDir
-    askinall "Press any key to start pre-make configuration: "
+    askinall "Press Enter to start pre-make configuration: "
     echo ""
-    echo ">> Performing pre-make configuration <<"
-    ./configure --prefix= --enable-eap-mschapv2 --enable-eap-identity --enable-openssl --enable-eap-md5 --enable-eap-tls --enable-eap-dynamic --enable-systemd --enable-swanctl --disable-charon --disable-stroke --disable-scepclient --enable-counters
+    echo "** $(date +'%Y-%m-%d %H:%M:%S') Performing pre-make configuration [Log: $PSDIR/pistrong-configure.log]"
+    ./configure --prefix= --enable-eap-mschapv2 --enable-eap-identity --enable-openssl --enable-eap-md5 --enable-eap-tls --enable-eap-dynamic --enable-systemd --enable-swanctl --disable-charon --disable-stroke --disable-scepclient --enable-counters > pistrong-configure.log
+    [ $? == 0 ] && sts="No errors" || sts="review pistrong-configure.log"
+    echo "   Config exit status: $? ($sts)"
 }
 
 function DoMake() {
     gotoBuildDir
-    askinall "Press any key to start make: "
+    askinall "Press Enter to start make: "
     echo ""
-    echo ">> Performing make <<"
-    make
+    echo "** $(date +'%Y-%m-%d %H:%M:%S') Performing make [Log: $PSDIR/pistrong-make.log]"
+    make > pistrong-make.log
+    [ $? == 0 ] && sts="No errors" || sts="review pistrong-make.log"
+    echo "   Make exit status: $? ($sts)"
 }
 
 function DoInstall() {
     gotoBuildDir
-    askinall "Press any key to start install: "
-    make install
+    askinall "Press Enter to start install: "
+    echo ""
+    echo "** $(date +'%Y-%m-%d %H:%M:%S') Performing install [Log: $PSDIR/pistrong-install.log]"
+    make install > pistrong-install.log 2>&1
+    [ $? == 0 ] && sts="No errors" || sts="review pistrong-install.log"
+    echo "   Install exit status: $? ($sts)"
+}
+
+function DoMakeDirs() {
+    echo "** Creating /etc/swanctl/pistrong directories..."
+    cd /etc/swanctl
+    [ ! -d conf.d ]   && mkdir conf.d
+    [ ! -d pistrong ] && mkdir pistrong && mkdir pistrong/{client-assets,server-assets,VPNClients,backup}
+    chmod 700 pistrong/client-assets pistrong/server-assets
+    [ ! -d "p12" ] && mkdir p12 && chmod 750 p12
 }
 
 function DoPostConf() {
-    [ "$cmd" == "allx" ] && echo "" && echo "Reached postconf at $(date)"
-    askinall "Press any key to start postconf: "
-    echo ""
-    [ ! -d "/etc/swanctl/conf.d" ] && mkdir -p /etc/swanctl/conf.d
-    fserver=1
+    [ "$cmd" == "allx" ] && echo "" && echo "** $(date +'%Y-%m-%d %H:%M:%S') Starting postconf"
+    [ "$cmd" != "postconf" -a "$cmd" != "post-configure" ] && askinall "Press Enter to start postconf: "
     echo ""
     echo " VPN Server configuration includes:"
     echo "   Enable IPV4 forwarding"
-    echo "   Write /etc/swanctl/pistrong/iptables"
-    echo "   Create (but not enabling) pistrong-iptables-load.service"
     echo ""
+    fserver=1
     if askyn "Configure this system to be a VPN Server"
     then
 	fserver=0
     fi
+    DoMakeDirs
+    sysctl92="/etc/sysctl.d/92-pistrong.conf"
+    sysctl92d="/etc/sysctl.d/.92-pistrong.conf"
     if [ $fserver -eq 0 ]
     then
-	echo ""
-	echo "The VPN Subnet is used by the VPN server for hosting clients"
-	echo "Suggest using a 10.*.*.* subnet although this is not mandatory"
-	echo "It must not conflict with any other local subnets"
-	echo ""
-	vpnsubnet="10.1.10.0/24"
-	echo -n "Subnet for VPN clients [$vpnsubnet]: " ; read ans
-	[ "$ans" != "" ] && vpnsubnet=$ans
-    fi
-    cd /etc/swanctl
-    [ ! -d pistrong ] && mkdir pistrong && mkdir pistrong/{client-assets,server-assets,VPNClients,backup}
-    chmod 700 pistrong/client-assets pistrong/server-assets
-    [ ! -d "p12" ] && mkdir p12 && chmod 750 p12
-
-    if [ ! -f "/etc/sysctl.d/92-pistrong.conf" ]
-    then
-	s="."
-	[ $fserver -eq 0 ] && s="" && echo ">> Creating /etc/sysctl.d/${s}92-pistrong.conf to set net.ipv4.ip_forward=1"
-	# Write it on client as well...but hidden
-	echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/${s}92-pistrong.conf
-	[ $fserver -eq 0 ] && sysctl -p /etc/sysctl.d/92-pistrong.conf > /dev/null
-    fi
-    [ $fserver -eq 0 ] && emitFirewall
-    # Tell systemd to reload the config files in case we wrote pistrong-iptables-load
-    systemctl daemon-reload
-    echo ">> pistrong/strongSwan Installation complete <<"
-    echo ">> "
-    echo ">> Required Post-installation Steps:"
-    if [ $fserver -eq 0 ]
-    then
-	echo ">>   Add router port forwards for UDP ports 500 and 4500 to this system"
-	echo ""
-	echo ">>   See https://github.com/gitbls/pistrong/blob/master/makeMyCA for a CA configuration script"
-	echo ">>   Use it if you need to support iOS, Windows, or Linux VPN Clients"
-	echo ""
-	echo ">>   Set up iptables. See https://github.com/gitbls/pistrong/blob/master/README.md#firewall-considerations"
-	echo ""
-	echo ">>   See pistrong help and pistrong --help for pistrong command details"
+	if [ ! -f $sysctl92 ]
+	then
+	    echo "** Creating $sysctl92 to set net.ipv4.ip_forward=1"
+	    echo "net.ipv4.ip_forward=1" > $sysctl92 && sysctl -p $sysctl92 > /dev/null
+	fi
     else
-	echo ">>   Once you have received the VPN Config Pack from the manager of the VPN Server"
-	echo ">>    install them into strongSwan using the 'sudo pistrong client install' command"
-	echo ">>   Then..."
+	# Write it on VPN clients as well...but hidden so not executed
+	[ ! -f $sysctl92d ] && echo "net.ipv4.ip_forward=1" > $sysctl92d
     fi
-    echo ""
-    echo ">>      'sudo pistrong service start' or 'sudo systemctl start strongswan' to start the strongSwan VPN"
-    echo ">>      'sudo pistrong service enable' or 'sudo systemctl enable strongswan' to enable strongSwan to restart after reboot"
-    echo ""
-    echo ">> Reboot and make sure everything works"
-    echo ""
-}
+    # Change IKE logging to eliminate keep-alive message logging
+    if [ ! -f /etc/strongswan.d/orig-charon-systemd.conf ]
+    then
+	mv /etc/strongswan.d/charon-systemd.conf /etc/strongswan.d/orig-charon-systemd.conf
+	cat >> /etc/strongswan.d/charon-systemd.conf <<EOF
+charon-systemd {
 
+    # Section to configure native systemd journal logger, very similar to the
+    # syslog logger as described in LOGGER CONFIGURATION in strongswan.conf(5).
+    journal {
+
+        # Loglevel for a specific subsystem.
+        # <subsystem> = <default>
+
+        # Default loglevel.
+        # default = 1
+
+        # ** pistrong set IKE=1 to turn off keep-alive message logging
+	ike = 1
+
+    }
+}
+EOF
+    fi
+}
 function DoAll() {
     DoPreReqs
     DoDownload
@@ -299,11 +244,36 @@ function DoAll() {
     DoInstall
     fServer=0
     DoPostConf
+    echo ""
+    echo "** pistrong/strongSwan Installation complete"
+    echo ""
+    echo "** Required Post-installation Steps:"
+    if [ $fserver -eq 0 ]
+    then
+	echo "     Add router port forwards for UDP ports 500 and 4500 to this system"
+	echo ""
+	echo "     See https://github.com/gitbls/pistrong/blob/master/makeMyCA to fully configure a CA"
+	echo "     that supports iOS, Windows, and Linux VPN Clients"
+	echo ""
+	echo "     Set up iptables. See https://github.com/gitbls/pistrong/blob/master/README.md#firewall-considerations"
+	echo ""
+	echo "     See pistrong help and pistrong --help for pistrong command details"
+    else
+	echo "     Once you have received the VPN Config Pack from the manager of the VPN Server"
+	echo "      install them into strongSwan using the 'sudo pistrong client install' command"
+	echo "     Then..."
+    fi
+    echo ""
+    echo "        'sudo pistrong service start' or 'sudo systemctl start strongswan' to start the strongSwan VPN"
+    echo "        'sudo pistrong service enable' or 'sudo systemctl enable strongswan' to enable strongSwan to restart after reboot"
+    echo ""
+    echo "   Reboot and make sure everything works"
+    echo ""
+
 }
 #
 # Main
 #
-
 if [[ ! $EUID -eq 0 ]];then
     echo "? Please run as root: sudo $0 $1 $2"
     exit 1
@@ -311,6 +281,10 @@ fi
 
 cmd="$1"
 [ "$cmd" == "" ] && cmd="all"
+[ "$PISTRONGROOT" == "" ] && PISTRONGROOT="/root"
+[ ! -d "$PISTRONGROOT" ] && echo "? PISTRONGROOT directory '$PISTRONGROOT' does not exist" && exit
+PSDIR="$PISTRONGROOT/piStrong"
+
 case "$cmd" in
     "prereq")   DoPreReqs ;;
     "download") DoDownload ;;
@@ -318,6 +292,7 @@ case "$cmd" in
     "make") DoMake ;;
     "install") DoInstall ;;
     "postconf"|"post-configure") DoPostConf ;;
+    "makedirs"|"mkdir") DoMakeDirs ;;
     "all"|"allx") DoAll ;;
     *) echo "? Invalid command" ;
        echo "? Commands: prereq|download|preconf|make|install|postconf|all" ;
